// Generated by https://quicktype.io

import { PaginationModel } from "../shared/models/pagination.model";

export interface PurchaseModel {
  productId: number;
  quantity: number;
  purchaseDate: string;
  description: string;
  price: number;
  productName: string;
  id: number;
  createDate: string;
  updateDate: string;
  isDeleted: boolean;
}

export interface PaginatedPurchase extends PaginationModel {
  purchases: PurchaseModel[];
}
