// Generated by https://quicktype.io

import { PaginationModel } from "../shared/models/pagination.model";

export interface SaleModel {
  productId: number;
  quantity: number;
  price: number;
  sellingDate: string;
  description: string;
  productName: string;
  id: number;
  createDate: string;
  updateDate: string;
  isDeleted: boolean;
}

export interface PaginatedSale extends PaginationModel {
  sales: SaleModel[];
}
