// Generated by https://quicktype.io

export interface SaleModel {
  productId: number;
  quantity: number;
  price: number;
  sellingDate: string;
  description: string;
  productName: string;
  id: number;
  createDate: string;
  updateDate: string;
  isDeleted: boolean;
}
