// Generated by https://quicktype.io

import { PaginationModel } from "../shared/models/pagination.model";

export interface Product {
  id: number;
  productName: string;
  categoryId: number;
  price: number;
  createDate?: string;
  updateDate?: string;
  isDeleted?: boolean;
  categoryName?: string;
}

export interface PaginatedProduct extends PaginationModel {
  products: Product[];
}
